let
    Source = Csv.Document(File.Contents("C:\Users\sarun\OneDrive\Desktop\o365mokykla_2020-2021_grupes_pradinis.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}}),
    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Guid", type text}, {"Identity", type text}, {"Id", type text}, {"Name", type text}, {"DisplayName", type text}, {"Alias", type text}, {"EmailAddresses", type text}, {"PrimarySmtpAddress", type text}, {"WindowsEmailAddress", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","12a","13a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","12b","13b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","12c","13c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","12d","13d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","12e","13e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","12f","13f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","12g","13g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","12h","13h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","11a","12a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","11b","12b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","11c","12c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","11d","12d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","11e","12e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","11f","12f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","11g","12g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","11h","12h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","10a","11a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","10b","11b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","10c","11c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","10d","11d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","10e","11e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","10f","11f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","10g","11g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","10h","11h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","9a","10a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","9b","10b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","9c","10c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","9d","10d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","9e","10e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","9f","10f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","9g","10g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","9h","10h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","8a","9a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","8b","9b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","8c","9c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","8d","9d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35","8e","9e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","8f","9f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value38" = Table.ReplaceValue(#"Replaced Value37","8g","9g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","8h","9h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","7a","8a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value41" = Table.ReplaceValue(#"Replaced Value40","7b","8b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value42" = Table.ReplaceValue(#"Replaced Value41","7c","8c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value43" = Table.ReplaceValue(#"Replaced Value42","7d","8d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","7e","8e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value45" = Table.ReplaceValue(#"Replaced Value44","7f","8f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value46" = Table.ReplaceValue(#"Replaced Value45","7g","8g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value47" = Table.ReplaceValue(#"Replaced Value46","7h","8h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value48" = Table.ReplaceValue(#"Replaced Value47","6a","7a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value49" = Table.ReplaceValue(#"Replaced Value48","6b","7b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value50" = Table.ReplaceValue(#"Replaced Value49","6c","7c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value51" = Table.ReplaceValue(#"Replaced Value50","6d","7d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value52" = Table.ReplaceValue(#"Replaced Value51","6e","7e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value53" = Table.ReplaceValue(#"Replaced Value52","6f","7f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value54" = Table.ReplaceValue(#"Replaced Value53","6g","7g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value55" = Table.ReplaceValue(#"Replaced Value54","6h","7h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value56" = Table.ReplaceValue(#"Replaced Value55","5a","6a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value57" = Table.ReplaceValue(#"Replaced Value56","5b","6b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value58" = Table.ReplaceValue(#"Replaced Value57","5c","6c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value59" = Table.ReplaceValue(#"Replaced Value58","5d","6d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value60" = Table.ReplaceValue(#"Replaced Value59","5e","6e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value61" = Table.ReplaceValue(#"Replaced Value60","5f","6f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value62" = Table.ReplaceValue(#"Replaced Value61","5g","6g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value63" = Table.ReplaceValue(#"Replaced Value62","5h","6h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value64" = Table.ReplaceValue(#"Replaced Value63","4a","5a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value65" = Table.ReplaceValue(#"Replaced Value64","4b","5b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value66" = Table.ReplaceValue(#"Replaced Value65","4c","5c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value67" = Table.ReplaceValue(#"Replaced Value66","4d","5d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value68" = Table.ReplaceValue(#"Replaced Value67","4e","5e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value69" = Table.ReplaceValue(#"Replaced Value68","4f","5f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value70" = Table.ReplaceValue(#"Replaced Value69","4g","5g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value71" = Table.ReplaceValue(#"Replaced Value70","4h","5h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value72" = Table.ReplaceValue(#"Replaced Value71","3a","4a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value73" = Table.ReplaceValue(#"Replaced Value72","3b","4b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value74" = Table.ReplaceValue(#"Replaced Value73","3c","4c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value75" = Table.ReplaceValue(#"Replaced Value74","3d","4d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value76" = Table.ReplaceValue(#"Replaced Value75","3e","4e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value77" = Table.ReplaceValue(#"Replaced Value76","3f","4f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value78" = Table.ReplaceValue(#"Replaced Value77","3g","4g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value79" = Table.ReplaceValue(#"Replaced Value78","3h","4h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value80" = Table.ReplaceValue(#"Replaced Value79","2a","3a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value81" = Table.ReplaceValue(#"Replaced Value80","2b","3b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value82" = Table.ReplaceValue(#"Replaced Value81","2c","3c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value83" = Table.ReplaceValue(#"Replaced Value82","2d","3d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value84" = Table.ReplaceValue(#"Replaced Value83","2e","3e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value85" = Table.ReplaceValue(#"Replaced Value84","2f","3f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value86" = Table.ReplaceValue(#"Replaced Value85","2g","3g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value87" = Table.ReplaceValue(#"Replaced Value86","2h","3h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value88" = Table.ReplaceValue(#"Replaced Value87","1a","2a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value89" = Table.ReplaceValue(#"Replaced Value88","1b","2b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value90" = Table.ReplaceValue(#"Replaced Value89","1c","2c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value91" = Table.ReplaceValue(#"Replaced Value90","1d","2d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value92" = Table.ReplaceValue(#"Replaced Value91","1e","2e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value93" = Table.ReplaceValue(#"Replaced Value92","1f","2f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value94" = Table.ReplaceValue(#"Replaced Value93","1g","2g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value95" = Table.ReplaceValue(#"Replaced Value94","1h","2h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value96" = Table.ReplaceValue(#"Replaced Value95","IVa","Va",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value97" = Table.ReplaceValue(#"Replaced Value96","IVb","Vb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value98" = Table.ReplaceValue(#"Replaced Value97","IVc","Vc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value99" = Table.ReplaceValue(#"Replaced Value98","IVd","Vd",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value100" = Table.ReplaceValue(#"Replaced Value99","IVe","Ve",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value101" = Table.ReplaceValue(#"Replaced Value100","IVf","Vf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value102" = Table.ReplaceValue(#"Replaced Value101","IVg","Vg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value103" = Table.ReplaceValue(#"Replaced Value102","IVh","Vh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value104" = Table.ReplaceValue(#"Replaced Value103","IIIa","IVa",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value105" = Table.ReplaceValue(#"Replaced Value104","IIIb","IVb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value106" = Table.ReplaceValue(#"Replaced Value105","IIIc","IVc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value107" = Table.ReplaceValue(#"Replaced Value106","IIId","IVd",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value108" = Table.ReplaceValue(#"Replaced Value107","IIIe","IVe",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value109" = Table.ReplaceValue(#"Replaced Value108","IIIf","IVf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value110" = Table.ReplaceValue(#"Replaced Value109","IIIg","IVg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value111" = Table.ReplaceValue(#"Replaced Value110","IIIh","IVh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value112" = Table.ReplaceValue(#"Replaced Value111","IIa","IIIa",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value113" = Table.ReplaceValue(#"Replaced Value112","IIb","IIIb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value114" = Table.ReplaceValue(#"Replaced Value113","IIc","IIIc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value115" = Table.ReplaceValue(#"Replaced Value114","IId","IIId",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value116" = Table.ReplaceValue(#"Replaced Value115","IIe","IIIe",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value117" = Table.ReplaceValue(#"Replaced Value116","IIf","IIIf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value118" = Table.ReplaceValue(#"Replaced Value117","IIg","IIIg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value119" = Table.ReplaceValue(#"Replaced Value118","IIh","IIIh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value120" = Table.ReplaceValue(#"Replaced Value119","Ia","IIa",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value121" = Table.ReplaceValue(#"Replaced Value120","Ib","IIb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value122" = Table.ReplaceValue(#"Replaced Value121","Ic","IIc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value123" = Table.ReplaceValue(#"Replaced Value122","Id","IId",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value124" = Table.ReplaceValue(#"Replaced Value123","Ie","IIe",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value125" = Table.ReplaceValue(#"Replaced Value124","If","IIf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value126" = Table.ReplaceValue(#"Replaced Value125","Ig","IIg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Replaced Value127" = Table.ReplaceValue(#"Replaced Value126","Ih","IIh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Sorted Rows" = Table.Sort(#"Replaced Value127",{{"Identity", Order.Descending}})
in
    #"Sorted Rows"
