let
    Šaltinis = Csv.Document(File.Contents("C:\Users\o365admin\Desktop\o365mokykla_2020-2021_grupes_pradinis.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Pakeistas tipas" = Table.TransformColumnTypes(Šaltinis,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}}),
    #"Pašalintos viršutinės eilutės" = Table.Skip(#"Pakeistas tipas",1),
    #"Į aukštesnį lygį perkeltos antraštės" = Table.PromoteHeaders(#"Pašalintos viršutinės eilutės", [PromoteAllScalars=true]),
    #"Pakeistas tipas1" = Table.TransformColumnTypes(#"Į aukštesnį lygį perkeltos antraštės",{{"Guid", type text}, {"Identity", type text}, {"Id", type text}, {"Name", type text}, {"DisplayName", type text}, {"Alias", type text}, {"EmailAddresses", type text}, {"PrimarySmtpAddress", type text}, {"WindowsEmailAddress", type text}}),
    #"Pakeista reikšmė" = Table.ReplaceValue(#"Pakeistas tipas1","12a","13a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė1" = Table.ReplaceValue(#"Pakeista reikšmė","12b","13b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė2" = Table.ReplaceValue(#"Pakeista reikšmė1","12c","13c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė3" = Table.ReplaceValue(#"Pakeista reikšmė2","12d","13d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė4" = Table.ReplaceValue(#"Pakeista reikšmė3","12e","13e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė5" = Table.ReplaceValue(#"Pakeista reikšmė4","12f","13f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė6" = Table.ReplaceValue(#"Pakeista reikšmė5","12g","13g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė7" = Table.ReplaceValue(#"Pakeista reikšmė6","12h","13h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė8" = Table.ReplaceValue(#"Pakeista reikšmė7","11a","12a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė9" = Table.ReplaceValue(#"Pakeista reikšmė8","11b","12b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė10" = Table.ReplaceValue(#"Pakeista reikšmė9","11c","12c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė11" = Table.ReplaceValue(#"Pakeista reikšmė10","11d","12d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė12" = Table.ReplaceValue(#"Pakeista reikšmė11","11e","12e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė13" = Table.ReplaceValue(#"Pakeista reikšmė12","11f","12f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė14" = Table.ReplaceValue(#"Pakeista reikšmė13","11g","12g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė15" = Table.ReplaceValue(#"Pakeista reikšmė14","11h","12h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė16" = Table.ReplaceValue(#"Pakeista reikšmė15","10a","11a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė17" = Table.ReplaceValue(#"Pakeista reikšmė16","10b","11b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė18" = Table.ReplaceValue(#"Pakeista reikšmė17","10c","11c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė19" = Table.ReplaceValue(#"Pakeista reikšmė18","10d","11d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė20" = Table.ReplaceValue(#"Pakeista reikšmė19","10e","11e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė21" = Table.ReplaceValue(#"Pakeista reikšmė20","10f","11f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė22" = Table.ReplaceValue(#"Pakeista reikšmė21","10g","11g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė23" = Table.ReplaceValue(#"Pakeista reikšmė22","10h","11h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė24" = Table.ReplaceValue(#"Pakeista reikšmė23","9a","10a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė25" = Table.ReplaceValue(#"Pakeista reikšmė24","9b","10b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė26" = Table.ReplaceValue(#"Pakeista reikšmė25","9c","10c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė27" = Table.ReplaceValue(#"Pakeista reikšmė26","9d","10d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė28" = Table.ReplaceValue(#"Pakeista reikšmė27","9e","10e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė29" = Table.ReplaceValue(#"Pakeista reikšmė28","9f","10f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė30" = Table.ReplaceValue(#"Pakeista reikšmė29","9g","10g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė31" = Table.ReplaceValue(#"Pakeista reikšmė30","9h","10h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė32" = Table.ReplaceValue(#"Pakeista reikšmė31","8a","9a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė33" = Table.ReplaceValue(#"Pakeista reikšmė32","8b","9b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė34" = Table.ReplaceValue(#"Pakeista reikšmė33","8c","9c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė35" = Table.ReplaceValue(#"Pakeista reikšmė34","8d","9d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė36" = Table.ReplaceValue(#"Pakeista reikšmė35","8e","9e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė37" = Table.ReplaceValue(#"Pakeista reikšmė36","8f","9f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė38" = Table.ReplaceValue(#"Pakeista reikšmė37","8g","9g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė39" = Table.ReplaceValue(#"Pakeista reikšmė38","8h","9h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė40" = Table.ReplaceValue(#"Pakeista reikšmė39","7a","8a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė41" = Table.ReplaceValue(#"Pakeista reikšmė40","7b","8b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė42" = Table.ReplaceValue(#"Pakeista reikšmė41","7c","8c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė43" = Table.ReplaceValue(#"Pakeista reikšmė42","7d","8d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė44" = Table.ReplaceValue(#"Pakeista reikšmė43","7e","8e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė45" = Table.ReplaceValue(#"Pakeista reikšmė44","7f","8f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė46" = Table.ReplaceValue(#"Pakeista reikšmė45","7g","8g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė47" = Table.ReplaceValue(#"Pakeista reikšmė46","7h","8h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė48" = Table.ReplaceValue(#"Pakeista reikšmė47","6a","7a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė49" = Table.ReplaceValue(#"Pakeista reikšmė48","6b","7b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė50" = Table.ReplaceValue(#"Pakeista reikšmė49","6c","7c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė51" = Table.ReplaceValue(#"Pakeista reikšmė50","6d","7d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė52" = Table.ReplaceValue(#"Pakeista reikšmė51","6e","7e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė53" = Table.ReplaceValue(#"Pakeista reikšmė52","6f","7f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė54" = Table.ReplaceValue(#"Pakeista reikšmė53","6g","7g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė55" = Table.ReplaceValue(#"Pakeista reikšmė54","6h","7h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė56" = Table.ReplaceValue(#"Pakeista reikšmė55","5a","6a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė57" = Table.ReplaceValue(#"Pakeista reikšmė56","5b","6b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė58" = Table.ReplaceValue(#"Pakeista reikšmė57","5c","6c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė59" = Table.ReplaceValue(#"Pakeista reikšmė58","5d","6d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė60" = Table.ReplaceValue(#"Pakeista reikšmė59","5e","6e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė61" = Table.ReplaceValue(#"Pakeista reikšmė60","5f","6f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė62" = Table.ReplaceValue(#"Pakeista reikšmė61","5g","6g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė63" = Table.ReplaceValue(#"Pakeista reikšmė62","5h","6h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė64" = Table.ReplaceValue(#"Pakeista reikšmė63","4a","5a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė65" = Table.ReplaceValue(#"Pakeista reikšmė64","4b","5b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė66" = Table.ReplaceValue(#"Pakeista reikšmė65","4c","5c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė67" = Table.ReplaceValue(#"Pakeista reikšmė66","4d","5d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė68" = Table.ReplaceValue(#"Pakeista reikšmė67","4e","5e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė69" = Table.ReplaceValue(#"Pakeista reikšmė68","4f","5f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė70" = Table.ReplaceValue(#"Pakeista reikšmė69","4g","5g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė71" = Table.ReplaceValue(#"Pakeista reikšmė70","4h","5h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė72" = Table.ReplaceValue(#"Pakeista reikšmė71","3a","4a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė73" = Table.ReplaceValue(#"Pakeista reikšmė72","3b","4b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė74" = Table.ReplaceValue(#"Pakeista reikšmė73","3c","4c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė75" = Table.ReplaceValue(#"Pakeista reikšmė74","3d","4d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė76" = Table.ReplaceValue(#"Pakeista reikšmė75","3e","4e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė77" = Table.ReplaceValue(#"Pakeista reikšmė76","3f","4f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė78" = Table.ReplaceValue(#"Pakeista reikšmė77","3g","4g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė79" = Table.ReplaceValue(#"Pakeista reikšmė78","3h","4h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė80" = Table.ReplaceValue(#"Pakeista reikšmė79","2a","3a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė81" = Table.ReplaceValue(#"Pakeista reikšmė80","2b","3b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė82" = Table.ReplaceValue(#"Pakeista reikšmė81","2c","3c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė83" = Table.ReplaceValue(#"Pakeista reikšmė82","2d","3d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė84" = Table.ReplaceValue(#"Pakeista reikšmė83","2e","3e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė85" = Table.ReplaceValue(#"Pakeista reikšmė84","2f","3f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė86" = Table.ReplaceValue(#"Pakeista reikšmė85","2g","3g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė87" = Table.ReplaceValue(#"Pakeista reikšmė86","2h","3h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė88" = Table.ReplaceValue(#"Pakeista reikšmė87","1a","2a",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė89" = Table.ReplaceValue(#"Pakeista reikšmė88","1b","2b",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė90" = Table.ReplaceValue(#"Pakeista reikšmė89","1c","2c",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė91" = Table.ReplaceValue(#"Pakeista reikšmė90","1d","2d",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė92" = Table.ReplaceValue(#"Pakeista reikšmė91","1e","2e",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė93" = Table.ReplaceValue(#"Pakeista reikšmė92","1f","2f",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė94" = Table.ReplaceValue(#"Pakeista reikšmė93","1g","2g",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė95" = Table.ReplaceValue(#"Pakeista reikšmė94","1h","2h",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė96" = Table.ReplaceValue(#"Pakeista reikšmė95","IVa","Va",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė97" = Table.ReplaceValue(#"Pakeista reikšmė96","IVb","Vb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė98" = Table.ReplaceValue(#"Pakeista reikšmė97","IVc","Vc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė99" = Table.ReplaceValue(#"Pakeista reikšmė98","IVd","Vd",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė100" = Table.ReplaceValue(#"Pakeista reikšmė99","IVe","Ve",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė101" = Table.ReplaceValue(#"Pakeista reikšmė100","IVf","Vf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė102" = Table.ReplaceValue(#"Pakeista reikšmė101","IVg","Vg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė103" = Table.ReplaceValue(#"Pakeista reikšmė102","IVh","Vh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė104" = Table.ReplaceValue(#"Pakeista reikšmė103","IIIa","IVa",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė105" = Table.ReplaceValue(#"Pakeista reikšmė104","IIIb","IVb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė106" = Table.ReplaceValue(#"Pakeista reikšmė105","IIIc","IVc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė107" = Table.ReplaceValue(#"Pakeista reikšmė106","IIId","IVd",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė108" = Table.ReplaceValue(#"Pakeista reikšmė107","IIIe","IVe",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė109" = Table.ReplaceValue(#"Pakeista reikšmė108","IIIf","IVf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė110" = Table.ReplaceValue(#"Pakeista reikšmė109","IIIg","IVg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė111" = Table.ReplaceValue(#"Pakeista reikšmė110","IIIh","IVh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė112" = Table.ReplaceValue(#"Pakeista reikšmė111","IIa","IIIa",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė113" = Table.ReplaceValue(#"Pakeista reikšmė112","IIb","IIIb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė114" = Table.ReplaceValue(#"Pakeista reikšmė113","IIc","IIIc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė115" = Table.ReplaceValue(#"Pakeista reikšmė114","IId","IIId",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė116" = Table.ReplaceValue(#"Pakeista reikšmė115","IIe","IIIe",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė117" = Table.ReplaceValue(#"Pakeista reikšmė116","IIf","IIIf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė118" = Table.ReplaceValue(#"Pakeista reikšmė117","IIg","IIIg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė119" = Table.ReplaceValue(#"Pakeista reikšmė118","IIh","IIIh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė120" = Table.ReplaceValue(#"Pakeista reikšmė119","Ia","IIa",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė121" = Table.ReplaceValue(#"Pakeista reikšmė120","Ib","IIb",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė122" = Table.ReplaceValue(#"Pakeista reikšmė121","Ic","IIc",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė123" = Table.ReplaceValue(#"Pakeista reikšmė122","Id","IId",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė124" = Table.ReplaceValue(#"Pakeista reikšmė123","Ie","IIe",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė125" = Table.ReplaceValue(#"Pakeista reikšmė124","If","IIf",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė126" = Table.ReplaceValue(#"Pakeista reikšmė125","Ig","IIg",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Pakeista reikšmė127" = Table.ReplaceValue(#"Pakeista reikšmė126","Ih","IIh",Replacer.ReplaceText,{"Identity", "Id", "Name", "DisplayName", "Alias", "EmailAddresses", "PrimarySmtpAddress", "WindowsEmailAddress"}),
    #"Surikiuotos eilutės" = Table.Sort(#"Pakeista reikšmė127",{{"Identity", Order.Descending}})
in
    #"Surikiuotos eilutės"