let
    Source = Csv.Document(File.Contents("o365mokykla_2020-2021_mokiniai_pradinis.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Removed Top Rows" = Table.Skip(Source,1),
    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"UserPrincipalName", type text}, {"DisplayName", type text}, {"FirstName", type text}, {"LastName", type text}, {"Title", type text}, {"Department", type text}, {"City", type text}, {"Office", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","12","13",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","12","13",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","11","12",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","11","12",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","10","11",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","10","11",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","9","10",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","9","10",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","8","9",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","8","9",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","7","8",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","7","8",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","6","7",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","6","7",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","5","6",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","5","6",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","4","5",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","4","5",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","3","4",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","3","4",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","2","3",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","2","3",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","1","2",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","1","2",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","IV","V",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","IV","V",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","III","IV",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","III","IV",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","II","III",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","II","III",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","Ia","IIa",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","Ia","IIa",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","Ib","IIb",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","Ib","IIb",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","Ic","IIc",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","Ic","IIc",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35","Id","IId",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","Id","IId",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value38" = Table.ReplaceValue(#"Replaced Value37","Ie","IIe",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","Ie","IIe",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","If","IIf",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value41" = Table.ReplaceValue(#"Replaced Value40","If","IIf",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value42" = Table.ReplaceValue(#"Replaced Value41","Ig","IIg",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value43" = Table.ReplaceValue(#"Replaced Value42","Ig","IIg",Replacer.ReplaceText,{"Department"}),
    #"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","Ih","IIh",Replacer.ReplaceText,{"Title"}),
    #"Replaced Value45" = Table.ReplaceValue(#"Replaced Value44","Ih","IIh",Replacer.ReplaceText,{"Department"}),
    #"Sorted Rows" = Table.Sort(#"Replaced Value45",{{"Department", Order.Descending}})
in
    #"Sorted Rows"
